### ISSUE TITLE
line 295: declare: -A: invalid option

### ISSUE THREAD

**Issue by sohutek** [termux/termux-packaging#3]
./generate-bootstraps.sh --prefix /data/data/com.my.package/files/usr
this got me run into this error

line 295: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

Plz help me out of this. I'm not too clear

**Comment by ghost** [comment]
If your **bash** doesn't support associative arrays, then you can't use this script.

**Comment by ghost** [comment]
It works on any normal Linux distribution (e.g Ubuntu or ArchLinux) with up to date packages.

**Comment by sohutek** [comment]
@xeffyr thanks for your help. But i'm really new. I can't find a detailed documents about building my own bootstrap for my own application. I spent 2 weeks and can't do a thing. Can i ask you for help?

**Comment by ghost** [comment]
https://github.com/termux/termux-packages/wiki/For-maintainers#generating-bootstrap-archives - isn't enough ?

1. Setup **own** repository on some hosting, e.g. Bintray (https://bintray.com).
2. Upload all base bootstrap packages to your APT repository.
3. Modify generate-bootstraps.sh script for your needs.

We will not guide you for setting up stuff on hosting. On the Internet you can find a lot information about setting up webservers. If you decided to go with Bintray variant, then look on https://www.jfrog.com/confluence/display/BT/Welcome+to+JFrog+Bintray and https://www.jfrog.com/confluence/display/BT/Bintray+REST+API.

If you can't use hosting somehow, then **open the `generate-bootstraps.sh` with text editor and study its contents**. After finishing, go straightforward and extract built debs by hand and repack them into zip file according to algorithm from script (its easy, btw).

**We already gave you: app sources, preconfigured build environment, package build scripts, CI configuration, Bintray upload scripts. That's enough for getting started and that's everything that is used now.** What we should do else ? Setup repository specially for someone's needs ? Or copy-paste the third-party documentation for setting up hosting ? I guess effect will be same because you just "don't want to read long papers"...

***

Finally, it is not allowed to reuse our services by third-party projects. Termux forks **must** use own repository.
